# Generated by Django 3.1.7 on 2021-03-12 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Контент'),
            preserve_default=False,
        ),
    ]
