# Generated by Django 3.1.7 on 2021-03-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210312_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
    ]
