# Generated by Django 3.1.7 on 2021-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210314_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_project',
            field=models.FileField(blank=True, help_text='Не обязательно', null=True, upload_to='', verbose_name='Загрузка файлов проекта'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
