# Generated by Django 3.1.7 on 2021-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210326_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_project',
            field=models.FileField(blank=True, help_text='Не обязательно', null=True, upload_to='file_project/%y/%m/%d/', verbose_name='Загрузка файлов проекта'),
        ),
    ]
