# Generated by Django 3.1.7 on 2021-03-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210326_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Заполняется автоматически', verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('slug', models.SlugField(help_text='Заполняется автоматически', verbose_name='Url')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('short_description', models.TextField(help_text='Краткое описание книги, рекомендовано до 500 символов', verbose_name='Краткое описание')),
                ('book_file', models.FileField(upload_to='books/%y/%m/%d/', verbose_name='Файл с книгой')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.bookcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
