# Generated by Django 3.1.7 on 2021-03-13 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210313_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_technology',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Технология проекта'),
            preserve_default=False,
        ),
    ]
