# Generated by Django 3.1.7 on 2021-03-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_project_project_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
