# Generated by Django 3.1.7 on 2021-03-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210326_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='books/img/%y/%m/%d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
