# Generated by Django 3.1.7 on 2021-03-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Не обязательно, система подставит стандартное изображение', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
