# Generated by Django 3.1.7 on 2021-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, help_text='Не обязательно! Фото будет поставлено автоматически', null=True, upload_to='books/img/%y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
